
server:
  port: 8081
  tomcat:
      accept-count: 1000
      max-threads: 1000
      max-connections: 2000

spring:
  application:
    name: service0
  zipkin:
        base-url: http://localhost:8070
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/

#ribbon:
#  eureka:
#   enabled: false
#
#SERVICE1:
#  ribbon:
#    listOfServers: http://localhost:8085