server:
  port: 8085
  tomcat:
    accept-count: 1000
    max-threads: 1000
    max-connections: 2000

#服务注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
  instance:
    hostname: localhost   # 指定该Eureka实例的主机名
    prefer-ip-address: true

#监控
spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:8070

management:
  security:
    #http://localhost:8085/routes
    enabled: false
zuul:
  #禁用的filter
  TokenFilter:
    pre:
      disable: true
  #ignored-services: microservice-comsumer-movie-ribbon-withhystrix  ，不允许代理本服务
  routes:
    service0:
      path: /service0/**
      serviceId: service0
      stripPrefix: true
    service1:
      path: /service1/**
      serviceId: service1
      stripPrefix: true
    oauth2-client:
      path: /auth/**
      sensitiveHeaders:
      serviceId: oauth2-client
      stripPrefix: true
  add-proxy-headers: true
  host:
    max-per-route-connections: 3000
    max-total-connections: 3000

#负载均衡
ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 3000
  ReadTimeout: 3000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #缺省为1000


service1:
  ribbon:
    listOfServers: http://127.0.0.1:8084,http://localhost:8082,http://localhost:8081
oauth2-client:
  ribbon:
    listOfServers: http://localhost:8071

#http://localhost:8085/service1/common?token=123  负载


#oauth2 集成
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8070/oauth/token
      user-authorization-uri: http://localhost:8070/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://localhost:8070/user
      prefer-token-info: false
