
server:
  port: 8084
  tomcat:
      accept-count: 1000
      max-threads: 1000
      max-connections: 2000

spring:
  application:
    name: service2-feign
  zipkin:
      base-url: http://localhost:8070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
  instance:
      hostname: localhost
      ipAddress: localhost
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  healthcheck:
         enable: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

SERVICE1:
  ribbon:
   #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
    ConnectTimeout: 500 #请求连接超时时间
    ReadTimeout: 1000 #请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数
    listOfServers: http://localhost:8083,http://localhost:8082

#http://localhost:8084/common 负载